# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'design.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(758, 497)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.button_apply_filter = QtWidgets.QPushButton(self.centralwidget)
        self.button_apply_filter.setGeometry(QtCore.QRect(420, 60, 111, 31))
        self.button_apply_filter.setObjectName("button_apply_filter")
        self.button_cancel_filter = QtWidgets.QPushButton(self.centralwidget)
        self.button_cancel_filter.setGeometry(QtCore.QRect(540, 60, 111, 31))
        self.button_cancel_filter.setObjectName("button_cancel_filter")
        self.add_row = QtWidgets.QPushButton(self.centralwidget)
        self.add_row.setGeometry(QtCore.QRect(20, 380, 171, 61))
        self.add_row.setObjectName("add_row")
        self.del_row = QtWidgets.QPushButton(self.centralwidget)
        self.del_row.setGeometry(QtCore.QRect(200, 380, 171, 61))
        self.del_row.setObjectName("del_row")
        self.filter_arg = QtWidgets.QLineEdit(self.centralwidget)
        self.filter_arg.setGeometry(QtCore.QRect(70, 60, 131, 31))
        self.filter_arg.setObjectName("filter_arg")
        self.comboBox = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox.setGeometry(QtCore.QRect(120, 20, 141, 31))
        self.comboBox.setObjectName("comboBox")
        self.comboBox_2 = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox_2.setGeometry(QtCore.QRect(280, 60, 131, 31))
        self.comboBox_2.setObjectName("comboBox_2")
        self.select_table = QtWidgets.QLabel(self.centralwidget)
        self.select_table.setGeometry(QtCore.QRect(20, 20, 101, 21))
        self.select_table.setObjectName("select_table")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(20, 60, 47, 21))
        self.label_2.setObjectName("label_2")
        self.filter_col = QtWidgets.QLabel(self.centralwidget)
        self.filter_col.setGeometry(QtCore.QRect(220, 60, 51, 21))
        self.filter_col.setObjectName("filter_col")
        self.tableView = QtWidgets.QTableView(self.centralwidget)
        self.tableView.setGeometry(QtCore.QRect(20, 100, 631, 271))
        self.tableView.setObjectName("tableView")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 758, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.button_apply_filter.setText(_translate("MainWindow", "Применить"))
        self.button_cancel_filter.setText(_translate("MainWindow", "Отменить"))
        self.add_row.setText(_translate("MainWindow", "Добавить строку"))
        self.del_row.setText(_translate("MainWindow", "Удалить строку"))
        self.select_table.setText(_translate("MainWindow", "Выберите таблицу"))
        self.label_2.setText(_translate("MainWindow", "Фильтр"))
        self.filter_col.setText(_translate("MainWindow", "По полю"))
